# Generated by Django 4.1.2 on 2022-11-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='datos',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='mes',
            field=models.IntegerField(),
        ),
    ]
