# Generated by Django 4.1.2 on 2022-11-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSitio', '0002_semana_datos_alter_bebe_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='datos',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
