# Generated by Django 4.1.2 on 2022-12-01 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appSitio', '0005_madre_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='datos',
            field=models.TextField(default='DEFAULT VALUE', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
